# File Paths
base_video_folder: "C:\\Users\\Jackson\\Documents\\northwestern\\spiders\\dlc_proj\\Habro1_gap45_gain20-jmich-2023-09-18\\videos\\"
output_name: "simple_kalman.mp4"

ideal_pts: [[190.2, 453.5],
       [325.7, 574.2],
       [631.2, 537.4],
       [599.0, 275.5],
       [300.8, 288.1]]
points : [
    "pit",
    "top_corner",
    "top_waist",
    "bot_waist",
    "bot_corner",
]

# Pipeline Stages
pipeline:
  [

    {
      name: kalman_filter_2d,
      params: [1000, 10],
      kwargs: {},
      targets: ["pit", "bot_waist"]
    },
    
  ]