# File Paths
base_video_folder: "C:\\Users\\Jackson\\Documents\\northwestern\\spiders\\dlc_proj\\Habro1_gap45_gain20-jmich-2023-09-18\\videos\\"
output_name: "simple_kalman.mp4"

ideal_pts: [[190.25768647, 453.522568],
       [325.70858745, 574.28230165],
       [631.20260825, 537.41828323],
       [599.03480258, 275.56768098],
       [300.85975782, 288.11255928]]

points : [
    "pit",
    "top_corner",
    "top_waist",
    "bot_waist",
    "bot_corner",
]

# Pipeline Stages
pipeline:
  [

    {
      name: kalman_filter_2d,
      params: [1000, 10],
      kwargs: {},
      targets: ["pit", "bot_waist"]
    },
    
  ]