# File Paths
base_video_folder: "C:\\Users\\Jackson\\Documents\\northwestern\\spiders\\dlc_proj\\Habro1_gap45_gain20-jmich-2023-09-18\\videos\\"
output_name: "simple_kalman.mp4"

ideal_pts: [[190.2, 453.5],
       [325.7, 574.2],
       [631.2, 537.4],
       [599.0, 275.5],
       [300.8, 288.1]]

points : [
    "pit",
    "top_corner",
    "top_waist",
    "bot_waist",
    "bot_corner",
]

# Pipeline Stages
pipeline:
  [
    {
      name: from_fixed_filter,
      params: [675, 525, [800, 350]],
      kwargs: {},
      targets: ["pit"],
      linker: "lerp",
    },
    {
      name: conf_filter,
      params: [0.9],
      kwargs: {},
      linker: "lerp",
    },
    {
      name: kalman_filter_2d,
      params: [1000, 10],
      kwargs: {},
    },
    {
    #This is a good example of using all optional arguements for shape matching
      name: shape_filter,
      # these are the weights of the sides and angles loss values
      params: [0.00001, 0.1,],
      kwargs: {
          #name of the objective function to use, if this is not provided then it defaults to standard shape matching
          "objective": "linear_pit_objective_function",
          # a reference point so we know what a "good shape" is
          "base_pt": [
           [190.2, 453.5],
           [325.7, 574.2],
           [631.2, 537.4],
           [599.0, 275.5],
           [300.8, 288.1]
           ],
           # weights of all the side distances values, reference the image in the README to know what each value aligns with
           "side_weights": [1, 0, 1, 0, 1,],
           # Very similar to above but slightly different. instead of index 0 being the distance from "pit" to "top corner", angle_weights[0] is the angle between bot_corner -> pit -> top_corner. So to allow the pit to move more I have lowered the weights for angles that include the pit and for sides that include the pit.
           "angle_weights": [0.1, 0.1, 1, 1, 0.1,]
      },
    },
  ]
