# File Paths
image_folder: "C:\\Users\\Jackson\\Documents\\northwestern\\spiders\\data\\images\\Habro1_gap45_gain20_1_B"
flat_folder: "C:\\Users\\Jackson\\Documents\\northwestern\\spiders\\data\\images\\flats\\all\\Flats_and_Darks\\Flats_gap45_gain20"
output_name: "mean_demo"

# Video Settings
vid_start_index: 1000
num_images: 400
video_stride: 2
convert_to_gray: False
crop: [
  [500,-1],
  [800,-1]
]

# Pipeline Stages
pipeline:
  [
    {
       name: summarize,
       params: [],
        kwargs: {}
    },
    {
      # Name of method
      name: mean_divide_video,
      # Any positional arguments (for example blur takes a argument for the size of the blur kernel)
      params:
        [10],
      # keyword arguments
      kwargs: {}
    },
    {
      name: block_match,
      params: [],
      kwargs: {}
    },
    {
      name: sharpen,
      params: [],
      kwargs: {}
    },
    {
      name: adv_normalize,
      params: [0],
      kwargs: {}
    },
    {
       name: mul,
       params: [255],
        kwargs: {}
    },
  ]